//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhCongTac
    {
        public byte ID { get; set; }
        public string ThoiGian { get; set; }
        public string NoiCongTac { get; set; }
        public Nullable<byte> idThongTinGiangVien { get; set; }
        public string CongViecDamNhiem { get; set; }
    
        public virtual ThongTinGiangVien ThongTinGiangVien { get; set; }
    }
}
