//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinGiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinGiangVien()
        {
            this.DuAns = new HashSet<DuAn>();
            this.QuaTrinhCongTacs = new HashSet<QuaTrinhCongTac>();
            this.QuaTrinhDaoTaos = new HashSet<QuaTrinhDaoTao>();
        }
    
        public byte ID { get; set; }
        public string hoTen { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public byte idChucVu { get; set; }
        public string phongBan { get; set; }
        public string chuyenNganh { get; set; }
        public string DonViCongTac { get; set; }
        public string Anh { get; set; }
        public Nullable<byte> IdKhoa { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuAn> DuAns { get; set; }
        public virtual Khoa Khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhCongTac> QuaTrinhCongTacs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhDaoTao> QuaTrinhDaoTaos { get; set; }
    }
}
